name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  Service Account: ds-github-actions@tenacious-camp-357012.iam.gserviceaccount.com
  SERVICE_NAME: umang-books-api
  Artifact Registry: http://asia-south1-docker.pkg.dev/tenacious-camp-357012/cloud-run-source-deploy

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.10"

      # - name: Install dependencies and run tests
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt
      #     python manage.py test

      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: google-github-actions/auth@v0.4.0
        with:
          workload_identity_provider: "projects/${{ 660956715067 }}/locations/global/workloadIdentityPools/github-actions/providers/github"
          service_account: ds-github-actions@tenacious-camp-357012.iam.gserviceaccount.com

      - name: Build and Push Docker image
        run: |
          docker buildx build \
            --tag gcr.io/${{ ds-github-actions@tenacious-camp-357012 }}/umang-books-api:latest \
            --push .

      - name: Deploy to Google Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ${{ umang-books-api }}
          image: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
