name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  SERVICE_NAME: umang-books-api
  PROJECT_ID: tenacious-camp-357012
  REGION: asia-south1

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.10"

      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: "projects/660956715067/locations/global/workloadIdentityPools/github-actions/providers/github"
          service_account: ds-github-actions@tenacious-camp-357012.iam.gserviceaccount.com

      - name: Log in to Artifact Registry
        run: |
          gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://asia-south1-docker.pkg.dev

      - name: Build and Push Docker image
        run: |
          IMAGE="asia-south1-docker.pkg.dev/${{ env.PROJECT_ID }}/cloud-run-source-deploy/api-backend:latest"
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Deploy to Google Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: umang-books-api
          image: asia-south1-docker.pkg.dev/${{ env.PROJECT_ID }}/cloud-run-source-deploy/api-backend:latest
          region: ${{ env.REGION }}
